/**
 * USD Documentation Middleware
 *
 * Creates HTTP handlers for serving USD documentation.
 *
 * Security Note: The UI HTML generation uses innerHTML for rendering
 * documentation from the trusted spec object (generated by our own code).
 * User-provided content is properly escaped with escapeHtml().
 */

import type { Registry } from '../core/index.js'
import type { SchemaRegistry } from '../validation/index.js'
import type { LoadedChannel, LoadedRestResource } from '../server/fs-routes/index.js'
import type { USDDocument, USDDocumentation } from '../usd/index.js'
import type { OpenAPIDocument } from '../usd/export/openapi.js'
import {
  generateUSD,
  type USDGeneratorOptions,
  type USDGeneratorProtocolConfig,
} from './generators/usd-generator.js'
import type { LoadedTcpHandler } from './generators/tcp-generator.js'
import type { LoadedUdpHandler } from './generators/udp-generator.js'
import { exportOpenAPI } from '../usd/export/openapi.js'
import { dump as yamlStringify } from 'js-yaml'
import { generateUIHTML } from './ui/index.js'

// =============================================================================
// Types
// =============================================================================

/**
 * USD middleware configuration
 */
export interface USDMiddlewareConfig {
  /** Base path for documentation endpoints (default: '/docs') */
  basePath?: string

  /** API information */
  info?: {
    title?: string
    version?: string
    description?: string
    termsOfService?: string
    contact?: {
      name?: string
      url?: string
      email?: string
    }
    license?: {
      name: string
      url?: string
      identifier?: string
    }
    summary?: string
  }

  /** Server definitions */
  servers?: USDGeneratorOptions['servers']

  /** Protocols to include (auto-detected if not specified) */
  protocols?: USDGeneratorOptions['protocols']

  /** Global content types */
  contentTypes?: USDGeneratorOptions['contentTypes']

  /** Security schemes */
  securitySchemes?: USDGeneratorOptions['securitySchemes']

  /** Default security requirement */
  defaultSecurity?: USDGeneratorOptions['defaultSecurity']

  /** Tags for grouping */
  tags?: USDGeneratorOptions['tags']

  /** External documentation */
  externalDocs?: USDGeneratorOptions['externalDocs']

  /** Tag groups for hierarchical organization (like Redoc) */
  tagGroups?: Array<{
    name: string
    tags: string[]
    description?: string
    expanded?: boolean
  }>

  /** UI configuration */
  ui?: {
    theme?: 'light' | 'dark' | 'auto'
    primaryColor?: string
    logo?: string
    favicon?: string
    tryItOut?: boolean
    codeGeneration?: {
      enabled?: boolean
      languages?: ('typescript' | 'python' | 'go' | 'curl')[]
    }
    /** Hero section (landing page header) */
    hero?: {
      /** Main title (defaults to API title) */
      title?: string
      /** Subtitle/tagline */
      tagline?: string
      /** Background style */
      background?: 'gradient' | 'solid' | 'pattern' | 'image'
      /** Background image URL (if background is 'image') */
      backgroundImage?: string
      /** Call-to-action buttons */
      buttons?: Array<{
        text: string
        href?: string
        primary?: boolean
      }>
      /** Quick links section */
      quickLinks?: Array<{
        title: string
        description?: string
        href: string
        icon?: string
      }>
    }
    /** Sidebar configuration */
    sidebar?: {
      /** Show search */
      search?: boolean
      /** Expand all groups by default */
      expandAll?: boolean
      /** Show endpoint count badges */
      showCounts?: boolean
    }
  }

  /** Include standard error schemas */
  includeErrorSchemas?: boolean

  /** Include stream event schemas */
  includeStreamEventSchemas?: boolean

  /** JSON-RPC generation options */
  jsonrpc?: USDGeneratorOptions['jsonrpc']

  /** gRPC generation options */
  grpc?: USDGeneratorOptions['grpc']

  /** Documentation customization (portable with the spec) */
  documentation?: USDDocumentation
}

/**
 * USD documentation handlers
 */
export interface USDHandlers {
  /** Serve the main documentation UI */
  serveUI: () => Response
  /** Serve USD document as JSON */
  serveUSD: () => Response
  /** Serve USD document as YAML */
  serveUSDYaml: () => Response
  /** Serve pure OpenAPI 3.1 JSON (for Swagger UI compatibility) */
  serveOpenAPI: () => Response
  /** Get the USD document */
  getUSDDocument: () => USDDocument
  /** Get the OpenAPI document */
  getOpenAPIDocument: () => OpenAPIDocument
}

/**
 * Context for USD middleware
 */
export interface USDMiddlewareContext {
  /** Handler registry */
  registry: Registry
  /** Schema registry */
  schemaRegistry: SchemaRegistry
  /** WebSocket channels */
  channels?: Map<string, LoadedChannel>
  /** REST resources */
  restResources?: LoadedRestResource[]
  /** TCP handlers */
  tcpHandlers?: LoadedTcpHandler[]
  /** UDP handlers */
  udpHandlers?: LoadedUdpHandler[]
  /** Protocol configuration (jsonrpc/grpc detection) */
  protocolConfig?: USDGeneratorProtocolConfig
}

// =============================================================================
// Middleware Factory
// =============================================================================

/**
 * Create USD documentation handlers
 */
export function createUSDHandlers(
  ctx: USDMiddlewareContext,
  config: USDMiddlewareConfig = {}
): USDHandlers {
  const {
    basePath = '/docs',
    info,
    servers,
    protocols,
    contentTypes,
    securitySchemes,
    defaultSecurity,
    tags,
    externalDocs,
    jsonrpc,
    grpc,
    ui,
    documentation,
    includeErrorSchemas = true,
    includeStreamEventSchemas = true,
  } = config

  // Cache for generated documents
  let cachedUSD: USDDocument | null = null
  let cachedOpenAPI: OpenAPIDocument | null = null

  // Generate USD document (lazy)
  const getUSD = (): USDDocument => {
    if (cachedUSD) return cachedUSD

    const result = generateUSD(
      {
        registry: ctx.registry,
        schemaRegistry: ctx.schemaRegistry,
        channels: ctx.channels,
        restResources: ctx.restResources,
        tcpHandlers: ctx.tcpHandlers,
        udpHandlers: ctx.udpHandlers,
        protocolConfig: ctx.protocolConfig,
      },
      {
        info: {
          title: info?.title ?? 'API Documentation',
          version: info?.version ?? '1.0.0',
          description: info?.description,
          termsOfService: info?.termsOfService,
          contact: info?.contact,
          license: info?.license,
          summary: info?.summary,
        },
        servers,
        protocols,
        contentTypes,
        securitySchemes,
        defaultSecurity,
        tags,
        externalDocs,
        documentation,
        jsonrpc,
        grpc,
        includeErrorSchemas,
        includeStreamEventSchemas,
      }
    )

    cachedUSD = result.document
    return cachedUSD
  }

  // Generate OpenAPI document (lazy)
  const getOpenAPI = (): OpenAPIDocument => {
    if (cachedOpenAPI) return cachedOpenAPI

    const usd = getUSD()
    cachedOpenAPI = exportOpenAPI(usd, {
      stripExtensions: true,
      includeWebSocketAsWebhooks: false,
      includeRpcAsEndpoints: false,
      includeStreamsAsEndpoints: false,
    })

    return cachedOpenAPI
  }

  return {
    serveUI: () => {
      const html = generateUIHTML({
        doc: getUSD(),
        basePath,
        ui,
        tagGroups: config.tagGroups,
      })
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
        },
      })
    },

    serveUSD: () => {
      const doc = getUSD()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    serveUSDYaml: () => {
      const doc = getUSD()
      const yaml = yamlStringify(doc)
      return new Response(yaml, {
        headers: {
          'Content-Type': 'application/x-yaml',
        },
      })
    },

    serveOpenAPI: () => {
      const doc = getOpenAPI()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    getUSDDocument: getUSD,
    getOpenAPIDocument: getOpenAPI,
  }
}
