/**
 * USD Documentation Middleware
 *
 * Creates HTTP handlers for serving USD documentation.
 *
 * Security Note: The UI HTML generation uses innerHTML for rendering
 * documentation from the trusted spec object (generated by our own code).
 * User-provided content is properly escaped with escapeHtml().
 */

import type { Registry } from '../core/index.js'
import type { SchemaRegistry } from '../validation/index.js'
import type { LoadedChannel, LoadedRestResource } from '../server/fs-routes/index.js'
import type {
  USDDocument, USDDocumentation, USDTagGroup,
  USDPathItem, USDSchema, USDSecurityScheme, USDParameter, USDResponse, USDRequestBody, USDExample,
} from '../usd/index.js'
import type { OpenAPIDocument } from '../usd/export/openapi.js'
import { existsSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import {
  generateUSD,
  type USDGeneratorOptions,
  type USDGeneratorProtocolConfig,
} from './generators/usd-generator.js'
import {
  loadMarkdownDocs,
  mergeMarkdownDocumentation,
  resolveMarkdownDocsSource,
  type MarkdownDocsSource,
} from './markdown-loader.js'
import type { LoadedTcpHandler } from './generators/tcp-generator.js'
import type { LoadedUdpHandler } from './generators/udp-generator.js'
import { exportOpenAPI } from '../usd/export/openapi.js'
import { dump as yamlStringify } from 'js-yaml'
import { generateUICSS, generateUIHTML, generateUIRuntimeJS } from './ui/index.js'
import {
  createMarkdownDocsState,
  joinDocsEndpoint,
  normalizeDocsBasePath,
  type DocsState,
  type MarkdownDocsState,
} from './docs-state.js'

function readBuiltDocsRuntime(): string | null {
  return readBuiltDocsUIAsset('raffel-docs.js')
}

function readBuiltDocsUIAsset(fileName: 'raffel-docs.js' | 'marked-renderer.js' | 'protocol-console.js' | 'sidebar-tree.js' | 'code-block-toolbar.js' | 'page-nav.js' | 'search-modal.js' | 'marked.umd.js' | 'prism.js'): string | null {
  const assetUrl = new URL(`./ui/assets/${fileName}`, import.meta.url)
  if (!existsSync(assetUrl)) return null
  return readFileSync(assetUrl, 'utf8')
}

export function readDocsAsset(rootDir: string, relativePath: string): Response | null {
  if (!relativePath || relativePath.includes('\0')) return null
  const normalized = path.normalize(relativePath)
  if (!normalized || normalized.startsWith('..') || path.isAbsolute(normalized)) return null
  const assetPath = path.resolve(rootDir, normalized)
  const rootPath = path.resolve(rootDir)
  if (assetPath !== rootPath && !assetPath.startsWith(`${rootPath}${path.sep}`)) return null
  if (!existsSync(assetPath)) return null
  const stats = statSync(assetPath)
  if (!stats.isFile() || assetPath.toLowerCase().endsWith('.md')) return null

  return new Response(readFileSync(assetPath), {
    headers: {
      'Content-Type': contentTypeForAsset(assetPath),
      'Cache-Control': 'no-store',
    },
  })
}

function contentTypeForAsset(filePath: string): string {
  switch (path.extname(filePath).toLowerCase()) {
    case '.apng':
      return 'image/apng'
    case '.avif':
      return 'image/avif'
    case '.css':
      return 'text/css; charset=utf-8'
    case '.gif':
      return 'image/gif'
    case '.jpg':
    case '.jpeg':
      return 'image/jpeg'
    case '.js':
    case '.mjs':
      return 'application/javascript; charset=utf-8'
    case '.json':
      return 'application/json; charset=utf-8'
    case '.pdf':
      return 'application/pdf'
    case '.png':
      return 'image/png'
    case '.svg':
      return 'image/svg+xml'
    case '.txt':
      return 'text/plain; charset=utf-8'
    case '.webp':
      return 'image/webp'
    case '.woff':
      return 'font/woff'
    case '.woff2':
      return 'font/woff2'
    default:
      return 'application/octet-stream'
  }
}

function jsonResponse(data: unknown): Response {
  return new Response(JSON.stringify(data, null, 2), {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'no-store',
    },
  })
}

// =============================================================================
// Types
// =============================================================================

/**
 * USD middleware configuration
 */
export interface USDMiddlewareConfig {
  /** Base path for documentation endpoints (default: '/docs') */
  basePath?: string

  /** API information */
  info?: {
    title?: string
    version?: string
    description?: string
    termsOfService?: string
    contact?: {
      name?: string
      url?: string
      email?: string
    }
    license?: {
      name: string
      url?: string
      identifier?: string
    }
    summary?: string
  }

  /** Server definitions */
  servers?: USDGeneratorOptions['servers']

  /** Protocols to include (auto-detected if not specified) */
  protocols?: USDGeneratorOptions['protocols']

  /** Global content types */
  contentTypes?: USDGeneratorOptions['contentTypes']

  /** Security schemes */
  securitySchemes?: USDGeneratorOptions['securitySchemes']

  /** Default security requirement */
  defaultSecurity?: USDGeneratorOptions['defaultSecurity']

  /** Tags for grouping */
  tags?: USDGeneratorOptions['tags']

  /** External documentation */
  externalDocs?: USDGeneratorOptions['externalDocs']

  /** Tag groups for hierarchical organization (like Redoc) */
  tagGroups?: USDTagGroup[]

  /** UI configuration */
  ui?: {
    theme?: 'light' | 'dark' | 'custom' | 'auto'
    primaryColor?: string
    logo?: string
    favicon?: string
    customCss?: string | string[]
    tryItOut?: boolean
    codeGeneration?: {
      enabled?: boolean
      languages?: ('typescript' | 'python' | 'go' | 'curl')[]
    }
    /** Hero section (landing page header) */
    hero?: {
      /** Main title (defaults to API title) */
      title?: string
      /** Subtitle/tagline */
      tagline?: string
      /** Background style */
      background?: 'gradient' | 'solid' | 'pattern' | 'image'
      /** Background image URL (if background is 'image') */
      backgroundImage?: string
      /** Call-to-action buttons */
      buttons?: Array<{
        text: string
        href?: string
        primary?: boolean
      }>
      /** Quick links section */
      quickLinks?: Array<{
        title: string
        description?: string
        href: string
        icon?: string
      }>
    }
    /** Sidebar configuration */
    sidebar?: {
      /** Show search */
      search?: boolean
      /** Expand all groups by default */
      expandAll?: boolean
      /** Show endpoint count badges */
      showCounts?: boolean
      /** Show Markdown documentation pages in the sidebar */
      docsPages?: boolean
      /** Hide the sidebar entirely */
      hide?: boolean
      /** Declarative sidebar tree. Order and hierarchy are preserved as declared. */
      items?: Array<{ title: string; path?: string; href?: string; children?: Array<{ title: string; path?: string; href?: string; children?: any[] }> }>
      /** file-backed Markdown heading depth to include under the active docs page */
      subMaxLevel?: number
    }
    /** Top navigation links */
    navbar?: Array<{ title: string; href?: string; external?: boolean; children?: Array<{ title: string; href?: string; external?: boolean }> }>
    /** Footer markdown/text */
    footer?: string
    /** In-page table of contents */
    toc?: { enabled?: boolean; minLevel?: number; maxLevel?: number }
    /** Markdown rendering behavior */
    markdown?: {
      autoHeader?: boolean
      formatUpdated?: string
      noEmoji?: boolean
      html?: 'escape' | 'raw'
      externalLinkTarget?: string
      externalLinkRel?: string
      noCompileLinks?: string[]
    }
    /** Skip navigation link text or toggle */
    skipLink?: boolean | string
    /** UI asset delivery mode */
    assets?: { mode?: 'inline' | 'external' }
    /**
     * Breadcrumb trail at the top of every Markdown / generated reference
     * page. `false` disables; `true` (default) enables with `hideOnHome: true`.
     */
    breadcrumbs?: boolean | { hideOnHome?: boolean }
  }

  /** Include standard error schemas */
  includeErrorSchemas?: boolean

  /** Include stream event schemas */
  includeStreamEventSchemas?: boolean

  /** JSON-RPC generation options */
  jsonrpc?: USDGeneratorOptions['jsonrpc']

  /** gRPC generation options */
  grpc?: USDGeneratorOptions['grpc']

  /** Documentation customization (portable with the spec) */
  documentation?: USDDocumentation

  /**
   * Markdown docs directory to load by convention.
   *
   * Supports file-backed Markdown files such as README.md, nested Markdown pages,
   * _sidebar.md, _navbar.md, _coverpage.md, and _404.md. Use `true` to
   * load the project's `./docs` directory.
   */
  docsDir?: MarkdownDocsSource

  /**
   * External paths to merge into the generated document.
   * Useful for injecting paths from plugins (e.g. s3db.js, auth routes).
   * Keys are OpenAPI path strings (e.g. '/users/{id}').
   */
  externalPaths?: Record<string, USDPathItem>

  /**
   * External components to merge into the generated document.
   * Each key is shallow-merged with the generated components of the same type.
   */
  externalComponents?: {
    schemas?: Record<string, USDSchema>
    securitySchemes?: Record<string, USDSecurityScheme | { $ref: string }>
    parameters?: Record<string, USDParameter | { $ref: string }>
    responses?: Record<string, USDResponse | { $ref: string }>
    requestBodies?: Record<string, USDRequestBody | { $ref: string }>
    examples?: Record<string, USDExample | { $ref: string }>
  }
}

/**
 * USD documentation handlers
 */
export interface USDHandlers {
  /** Serve the main documentation UI */
  serveUI: () => Response
  /** Serve Docs State as JSON */
  serveDocsState: () => Response
  /** Serve USD document as JSON */
  serveUSD: () => Response
  /** Serve USD document as YAML */
  serveUSDYaml: () => Response
  /** Serve pure OpenAPI 3.1 JSON (for Swagger UI compatibility) */
  serveOpenAPI: () => Response
  /** Serve reusable docs UI JavaScript runtime */
  serveUIRuntime: () => Response
  /** Serve reusable Markdown engine support asset */
  serveUIMarkdownEngine: () => Response
  /** Serve reusable Prism.js syntax highlighter asset */
  serveUISyntaxHighlighter: () => Response
  /** Serve reusable Markdown renderer bridge */
  serveUIMarkdownRenderer: () => Response
  /** Serve reusable protocol console bridge */
  serveUIProtocolConsole: () => Response
  /** Serve reusable declarative sidebar runtime bridge */
  serveUISidebarTree: () => Response
  /** Serve reusable code-block toolbar runtime bridge */
  serveUICodeBlockToolbar: () => Response
  /** Serve reusable page-nav (prev/next) runtime bridge */
  serveUIPageNav: () => Response
  /** Serve reusable cmd+K search modal runtime bridge */
  serveUISearchModal: () => Response
  /** Serve docs UI stylesheet */
  serveUIStyles: () => Response
  /** Serve static assets referenced by Markdown docsDir pages */
  serveDocsAsset: (pathname: string) => Response | null
  /** Get the USD document */
  getUSDDocument: () => USDDocument
  /** Get the OpenAPI document */
  getOpenAPIDocument: () => OpenAPIDocument
  /** Get the Markdown Documentation state slice without regenerating API docs */
  getMarkdownDocsState: () => MarkdownDocsState
}

/**
 * Context for USD middleware
 */
export interface USDMiddlewareContext {
  /** Handler registry */
  registry: Registry
  /** Schema registry */
  schemaRegistry: SchemaRegistry
  /** WebSocket channels */
  channels?: Map<string, LoadedChannel>
  /** REST resources */
  restResources?: LoadedRestResource[]
  /** TCP handlers */
  tcpHandlers?: LoadedTcpHandler[]
  /** UDP handlers */
  udpHandlers?: LoadedUdpHandler[]
  /** Protocol configuration (jsonrpc/grpc detection) */
  protocolConfig?: USDGeneratorProtocolConfig
  /** Authorization snapshot (when policy is configured on the server) */
  authz?: {
    defaultMode: 'allow' | 'deny'
    policies: ReadonlyArray<{
      id: string
      description?: string
      effect: 'allow' | 'deny' | 'audit'
      principals: readonly string[]
      actions: readonly string[]
      resources: readonly string[]
      hasCondition: boolean
      match?: unknown
    }>
  }
  /** API contract revision used to invalidate generated docs caches. */
  getApiDocumentationRevision?: () => number
  /** Complete Docs State supplier owned by the server builder when available. */
  getDocsState?: () => Record<string, unknown>
}

// =============================================================================
// Middleware Factory
// =============================================================================

/**
 * Create USD documentation handlers
 */
export function createUSDHandlers(
  ctx: USDMiddlewareContext,
  config: USDMiddlewareConfig = {}
): USDHandlers {
  const {
    basePath = '/docs',
    info,
    servers,
    protocols,
    contentTypes,
    securitySchemes,
    defaultSecurity,
    tags,
    externalDocs,
    jsonrpc,
    grpc,
    ui,
    documentation,
    docsDir,
    includeErrorSchemas = true,
    includeStreamEventSchemas = true,
    externalPaths,
    externalComponents,
  } = config

  const docsHandlersCreatedAt = new Date().toISOString()
  const normalizedBasePath = normalizeDocsBasePath(basePath)
  const loadedMarkdownDocs = docsDir ? loadMarkdownDocs(docsDir) : undefined
  const markdownDocsSource = docsDir ? resolveMarkdownDocsSource(docsDir) : undefined
  const mergedDocumentation = mergeMarkdownDocumentation(documentation, loadedMarkdownDocs?.documentation)
  const mergedUI = loadedMarkdownDocs?.navbar && !ui?.navbar
    ? { ...ui, navbar: loadedMarkdownDocs.navbar }
    : ui

  // Cache for generated documents
  let cachedUSD: USDDocument | null = null
  let cachedOpenAPI: OpenAPIDocument | null = null
  let cachedUSDRevision = -1
  let cachedOpenAPIRevision = -1

  const currentApiRevision = () => ctx.getApiDocumentationRevision?.() ?? 0

  const getMarkdownDocsState = (): MarkdownDocsState => createMarkdownDocsState({
    basePath: normalizedBasePath,
    docsDir,
    documentation,
    loadedMarkdownDocs,
    markdownDocsSource,
    mergedDocumentation,
    mounted: true,
    loadedAt: docsHandlersCreatedAt,
    mountedAt: docsHandlersCreatedAt,
  })

  const getDefaultDocsState = (): DocsState => {
    const procedures = ctx.registry.listProcedures().length
    const restRoutes = (ctx.restResources ?? []).reduce((sum, resource) => sum + resource.routes.length, 0)
    return {
      generatedAt: new Date().toISOString(),
      api: {
        enabled: true,
        mounted: true,
        fresh: true,
        revision: currentApiRevision(),
        basePath: normalizedBasePath,
        endpoints: {
          ui: normalizedBasePath,
          usdJson: joinDocsEndpoint(normalizedBasePath, '/usd.json'),
          usdYaml: joinDocsEndpoint(normalizedBasePath, '/usd.yaml'),
          openApiJson: joinDocsEndpoint(normalizedBasePath, '/openapi.json'),
          state: joinDocsEndpoint(normalizedBasePath, '/state.json'),
        },
        routeCounts: {
          procedures,
          restRoutes,
          total: procedures + restRoutes,
        },
        updatedAt: null,
        mountedAt: docsHandlersCreatedAt,
        staleReasons: [],
      },
      markdown: getMarkdownDocsState(),
    }
  }

  // Generate USD document (lazy)
  const getUSD = (): USDDocument => {
    const revision = currentApiRevision()
    if (cachedUSD && cachedUSDRevision === revision) return cachedUSD

    const result = generateUSD(
      {
        registry: ctx.registry,
        schemaRegistry: ctx.schemaRegistry,
        channels: ctx.channels,
        restResources: ctx.restResources,
        tcpHandlers: ctx.tcpHandlers,
        udpHandlers: ctx.udpHandlers,
        protocolConfig: ctx.protocolConfig,
        ...(ctx.authz ? { authz: ctx.authz } : {}),
      },
      {
        info: {
          title: info?.title ?? 'API Documentation',
          version: info?.version ?? '1.0.0',
          description: info?.description,
          termsOfService: info?.termsOfService,
          contact: info?.contact,
          license: info?.license,
          summary: info?.summary,
        },
        servers,
        protocols,
        contentTypes,
        securitySchemes,
        defaultSecurity,
        tags,
        externalDocs,
        documentation: mergedDocumentation,
        tagGroups: config.tagGroups,
        jsonrpc,
        grpc,
        includeErrorSchemas,
        includeStreamEventSchemas,
        externalPaths,
        externalComponents,
      }
    )

    cachedUSD = result.document
    cachedUSDRevision = revision
    return cachedUSD
  }

  // Generate OpenAPI document (lazy)
  const getOpenAPI = (): OpenAPIDocument => {
    const revision = currentApiRevision()
    if (cachedOpenAPI && cachedOpenAPIRevision === revision) return cachedOpenAPI

    const usd = getUSD()
    cachedOpenAPI = exportOpenAPI(usd, {
      stripExtensions: true,
      includeWebSocketAsWebhooks: false,
      includeRpcAsEndpoints: false,
      includeStreamsAsEndpoints: false,
    })
    cachedOpenAPIRevision = revision

    return cachedOpenAPI
  }

  return {
    serveUI: () => {
      const html = generateUIHTML({
        doc: getUSD(),
        basePath,
        ui: mergedUI,
        tagGroups: config.tagGroups,
      })
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-store',
        },
      })
    },

    serveDocsState: () => jsonResponse(ctx.getDocsState?.() ?? getDefaultDocsState()),

    serveUSD: () => {
      const doc = getUSD()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    serveUSDYaml: () => {
      const doc = getUSD()
      const yaml = yamlStringify(doc)
      return new Response(yaml, {
        headers: {
          'Content-Type': 'application/x-yaml',
        },
      })
    },

    serveOpenAPI: () => {
      const doc = getOpenAPI()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    serveUIRuntime: () => {
      const runtime = readBuiltDocsRuntime() ?? generateUIRuntimeJS()
      return new Response(runtime, {
        headers: {
          'Content-Type': 'application/javascript; charset=utf-8',
          'Cache-Control': 'no-store',
        },
      })
    },

    serveUIMarkdownEngine: () => new Response(readBuiltDocsUIAsset('marked.umd.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUISyntaxHighlighter: () => new Response(readBuiltDocsUIAsset('prism.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUIMarkdownRenderer: () => new Response(readBuiltDocsUIAsset('marked-renderer.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUIProtocolConsole: () => new Response(readBuiltDocsUIAsset('protocol-console.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUICodeBlockToolbar: () => new Response(readBuiltDocsUIAsset('code-block-toolbar.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUIPageNav: () => new Response(readBuiltDocsUIAsset('page-nav.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUISearchModal: () => new Response(readBuiltDocsUIAsset('search-modal.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUISidebarTree: () => new Response(readBuiltDocsUIAsset('sidebar-tree.js') ?? '', {
      headers: {
        'Content-Type': 'application/javascript; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    }),

    serveUIStyles: () => {
      const css = generateUICSS({
        doc: getUSD(),
        basePath,
        ui: mergedUI,
        tagGroups: config.tagGroups,
      })
      return new Response(css, {
        headers: {
          'Content-Type': 'text/css; charset=utf-8',
          'Cache-Control': 'no-store',
        },
      })
    },

    serveDocsAsset: (pathname: string) => {
      if (!markdownDocsSource) return null
      const prefix = `${basePath.replace(/\/$/, '')}/-/assets/`
      if (!pathname.startsWith(prefix)) return null
      const relativePath = decodeURIComponent(pathname.slice(prefix.length))
      const response = readDocsAsset(markdownDocsSource.rootDir, relativePath)
      return response
    },

    getUSDDocument: getUSD,
    getOpenAPIDocument: getOpenAPI,
    getMarkdownDocsState,
  }
}

// =============================================================================
// mountUSDDocs — convenience helper
// =============================================================================

/**
 * Minimal app shape `mountUSDDocs` needs: a `.get(path, handler)` that wires
 * a request handler. Works with `HttpApp` and any router that exposes a
 * compatible `.get(path, handler)` method.
 */
export interface USDDocsApp {
  get(path: string, handler: (c: { req: Request | { url: string } }) => Response | Promise<Response>): unknown
}

/**
 * Mount the full USD documentation surface on an HttpApp (or any
 * `.get(path, handler)`-shaped app) with a single call.
 *
 * Wires every internal asset route (`<basePath>/-/raffel-docs.{js,css}`,
 * `marked.umd.js`, `prism.js`, `marked-renderer.js`, `protocol-console.js`,
 * `sidebar-tree.js`), the spec endpoints (`<basePath>/openapi.json`,
 * `usd.json`, `usd.yaml`), the static markdown asset wildcard
 * (`<basePath>/-/assets/*`), and finally the SPA wildcard (`<basePath>/*`).
 *
 * Order matters: the SPA wildcard is registered last so individual asset
 * lookups never get caught by it. The list of internal assets is owned by
 * Raffel — consumers should not need to know it.
 *
 * @example
 * ```ts
 * import { HttpApp } from 'raffel/http'
 * import { mountUSDDocs } from 'raffel/docs'
 *
 * const app = new HttpApp()
 * mountUSDDocs(app, { registry, schemaRegistry }, { basePath: '/coding' })
 * ```
 */
export function mountUSDDocs(
  app: USDDocsApp,
  ctx: USDMiddlewareContext,
  config: USDMiddlewareConfig = {},
): USDHandlers {
  const handlers = createUSDHandlers(ctx, config)
  const basePath = (config.basePath ?? '/docs').replace(/\/$/, '') || '/docs'

  const reply = (fn: () => Response) => () => fn()
  const replyOrFallback = (
    fn: (pathname: string) => Response | null,
  ) => (c: { req: { url: string } }) => {
    const url = new URL(c.req.url, 'http://x')
    const out = fn(url.pathname)
    return out ?? new Response(null, { status: 404 })
  }

  // Internal assets — registered first so the SPA wildcard never shadows them.
  app.get(`${basePath}/-/raffel-docs.css`, reply(() => handlers.serveUIStyles()))
  app.get(`${basePath}/-/raffel-docs.js`, reply(() => handlers.serveUIRuntime()))
  app.get(`${basePath}/-/marked.umd.js`, reply(() => handlers.serveUIMarkdownEngine()))
  app.get(`${basePath}/-/prism.js`, reply(() => handlers.serveUISyntaxHighlighter()))
  app.get(`${basePath}/-/marked-renderer.js`, reply(() => handlers.serveUIMarkdownRenderer()))
  app.get(`${basePath}/-/protocol-console.js`, reply(() => handlers.serveUIProtocolConsole()))
  app.get(`${basePath}/-/sidebar-tree.js`, reply(() => handlers.serveUISidebarTree()))
  app.get(`${basePath}/-/code-block-toolbar.js`, reply(() => handlers.serveUICodeBlockToolbar()))
  app.get(`${basePath}/-/page-nav.js`, reply(() => handlers.serveUIPageNav()))
  app.get(`${basePath}/-/search-modal.js`, reply(() => handlers.serveUISearchModal()))

  // Spec endpoints.
  app.get(`${basePath}/state.json`, reply(() => handlers.serveDocsState()))
  app.get(`${basePath}/openapi.json`, reply(() => handlers.serveOpenAPI()))
  app.get(`${basePath}/usd.json`, reply(() => handlers.serveUSD()))
  app.get(`${basePath}/usd.yaml`, reply(() => handlers.serveUSDYaml()))

  // Static Markdown assets (images / extra JS shipped with the docs dir).
  app.get(`${basePath}/-/assets/*`, replyOrFallback(handlers.serveDocsAsset))

  // SPA wildcard last — all unmatched docs paths render the UI shell.
  app.get(`${basePath}/*`, reply(() => handlers.serveUI()))

  return handlers
}
