/**
 * USD Documentation Middleware
 *
 * Creates HTTP handlers for serving USD documentation.
 *
 * Security Note: The UI HTML generation uses innerHTML for rendering
 * documentation from the trusted spec object (generated by our own code).
 * User-provided content is properly escaped with escapeHtml().
 */

import type { Registry } from '../core/index.js'
import type { SchemaRegistry } from '../validation/index.js'
import type { LoadedChannel, LoadedRestResource } from '../server/fs-routes/index.js'
import type {
  USDDocument, USDDocumentation, USDTagGroup,
  USDPathItem, USDSchema, USDSecurityScheme, USDParameter, USDResponse, USDRequestBody, USDExample,
} from '../usd/index.js'
import type { OpenAPIDocument } from '../usd/export/openapi.js'
import { existsSync, readFileSync } from 'node:fs'
import {
  generateUSD,
  type USDGeneratorOptions,
  type USDGeneratorProtocolConfig,
} from './generators/usd-generator.js'
import {
  loadMarkdownDocs,
  mergeMarkdownDocumentation,
  type MarkdownDocsSource,
} from './markdown-loader.js'
import type { LoadedTcpHandler } from './generators/tcp-generator.js'
import type { LoadedUdpHandler } from './generators/udp-generator.js'
import { exportOpenAPI } from '../usd/export/openapi.js'
import { dump as yamlStringify } from 'js-yaml'
import { generateUICSS, generateUIHTML, generateUIRuntimeJS } from './ui/index.js'

function readBuiltDocsRuntime(): string | null {
  const assetUrl = new URL('./ui/assets/raffel-docs.js', import.meta.url)
  if (!existsSync(assetUrl)) return null
  return readFileSync(assetUrl, 'utf8')
}

// =============================================================================
// Types
// =============================================================================

/**
 * USD middleware configuration
 */
export interface USDMiddlewareConfig {
  /** Base path for documentation endpoints (default: '/docs') */
  basePath?: string

  /** API information */
  info?: {
    title?: string
    version?: string
    description?: string
    termsOfService?: string
    contact?: {
      name?: string
      url?: string
      email?: string
    }
    license?: {
      name: string
      url?: string
      identifier?: string
    }
    summary?: string
  }

  /** Server definitions */
  servers?: USDGeneratorOptions['servers']

  /** Protocols to include (auto-detected if not specified) */
  protocols?: USDGeneratorOptions['protocols']

  /** Global content types */
  contentTypes?: USDGeneratorOptions['contentTypes']

  /** Security schemes */
  securitySchemes?: USDGeneratorOptions['securitySchemes']

  /** Default security requirement */
  defaultSecurity?: USDGeneratorOptions['defaultSecurity']

  /** Tags for grouping */
  tags?: USDGeneratorOptions['tags']

  /** External documentation */
  externalDocs?: USDGeneratorOptions['externalDocs']

  /** Tag groups for hierarchical organization (like Redoc) */
  tagGroups?: USDTagGroup[]

  /** UI configuration */
  ui?: {
    theme?: 'light' | 'dark' | 'auto'
    primaryColor?: string
    logo?: string
    favicon?: string
    tryItOut?: boolean
    codeGeneration?: {
      enabled?: boolean
      languages?: ('typescript' | 'python' | 'go' | 'curl')[]
    }
    /** Hero section (landing page header) */
    hero?: {
      /** Main title (defaults to API title) */
      title?: string
      /** Subtitle/tagline */
      tagline?: string
      /** Background style */
      background?: 'gradient' | 'solid' | 'pattern' | 'image'
      /** Background image URL (if background is 'image') */
      backgroundImage?: string
      /** Call-to-action buttons */
      buttons?: Array<{
        text: string
        href?: string
        primary?: boolean
      }>
      /** Quick links section */
      quickLinks?: Array<{
        title: string
        description?: string
        href: string
        icon?: string
      }>
    }
    /** Sidebar configuration */
    sidebar?: {
      /** Show search */
      search?: boolean
      /** Expand all groups by default */
      expandAll?: boolean
      /** Show endpoint count badges */
      showCounts?: boolean
      /** Show Markdown documentation pages in the sidebar */
      docsPages?: boolean
    }
    /** Top navigation links */
    navbar?: Array<{ title: string; href: string; external?: boolean }>
    /** Footer markdown/text */
    footer?: string
    /** In-page table of contents */
    toc?: { enabled?: boolean; minLevel?: number; maxLevel?: number }
    /** UI asset delivery mode */
    assets?: { mode?: 'inline' | 'external' }
  }

  /** Include standard error schemas */
  includeErrorSchemas?: boolean

  /** Include stream event schemas */
  includeStreamEventSchemas?: boolean

  /** JSON-RPC generation options */
  jsonrpc?: USDGeneratorOptions['jsonrpc']

  /** gRPC generation options */
  grpc?: USDGeneratorOptions['grpc']

  /** Documentation customization (portable with the spec) */
  documentation?: USDDocumentation

  /**
   * Markdown docs directory to load by convention.
   *
   * Supports Docsify-style files such as README.md, nested Markdown pages,
   * _sidebar.md, _navbar.md, _coverpage.md, and _404.md.
   */
  docsDir?: MarkdownDocsSource

  /**
   * External paths to merge into the generated document.
   * Useful for injecting paths from plugins (e.g. s3db.js, auth routes).
   * Keys are OpenAPI path strings (e.g. '/users/{id}').
   */
  externalPaths?: Record<string, USDPathItem>

  /**
   * External components to merge into the generated document.
   * Each key is shallow-merged with the generated components of the same type.
   */
  externalComponents?: {
    schemas?: Record<string, USDSchema>
    securitySchemes?: Record<string, USDSecurityScheme | { $ref: string }>
    parameters?: Record<string, USDParameter | { $ref: string }>
    responses?: Record<string, USDResponse | { $ref: string }>
    requestBodies?: Record<string, USDRequestBody | { $ref: string }>
    examples?: Record<string, USDExample | { $ref: string }>
  }
}

/**
 * USD documentation handlers
 */
export interface USDHandlers {
  /** Serve the main documentation UI */
  serveUI: () => Response
  /** Serve USD document as JSON */
  serveUSD: () => Response
  /** Serve USD document as YAML */
  serveUSDYaml: () => Response
  /** Serve pure OpenAPI 3.1 JSON (for Swagger UI compatibility) */
  serveOpenAPI: () => Response
  /** Serve reusable docs UI JavaScript runtime */
  serveUIRuntime: () => Response
  /** Serve docs UI stylesheet */
  serveUIStyles: () => Response
  /** Get the USD document */
  getUSDDocument: () => USDDocument
  /** Get the OpenAPI document */
  getOpenAPIDocument: () => OpenAPIDocument
}

/**
 * Context for USD middleware
 */
export interface USDMiddlewareContext {
  /** Handler registry */
  registry: Registry
  /** Schema registry */
  schemaRegistry: SchemaRegistry
  /** WebSocket channels */
  channels?: Map<string, LoadedChannel>
  /** REST resources */
  restResources?: LoadedRestResource[]
  /** TCP handlers */
  tcpHandlers?: LoadedTcpHandler[]
  /** UDP handlers */
  udpHandlers?: LoadedUdpHandler[]
  /** Protocol configuration (jsonrpc/grpc detection) */
  protocolConfig?: USDGeneratorProtocolConfig
  /** Authorization snapshot (when policy is configured on the server) */
  authz?: {
    defaultMode: 'allow' | 'deny'
    policies: ReadonlyArray<{
      id: string
      description?: string
      effect: 'allow' | 'deny' | 'audit'
      principals: readonly string[]
      actions: readonly string[]
      resources: readonly string[]
      hasCondition: boolean
      match?: unknown
    }>
  }
}

// =============================================================================
// Middleware Factory
// =============================================================================

/**
 * Create USD documentation handlers
 */
export function createUSDHandlers(
  ctx: USDMiddlewareContext,
  config: USDMiddlewareConfig = {}
): USDHandlers {
  const {
    basePath = '/docs',
    info,
    servers,
    protocols,
    contentTypes,
    securitySchemes,
    defaultSecurity,
    tags,
    externalDocs,
    jsonrpc,
    grpc,
    ui,
    documentation,
    docsDir,
    includeErrorSchemas = true,
    includeStreamEventSchemas = true,
    externalPaths,
    externalComponents,
  } = config

  const loadedMarkdownDocs = docsDir ? loadMarkdownDocs(docsDir) : undefined
  const mergedDocumentation = mergeMarkdownDocumentation(documentation, loadedMarkdownDocs?.documentation)
  const mergedUI = loadedMarkdownDocs?.navbar && !ui?.navbar
    ? { ...ui, navbar: loadedMarkdownDocs.navbar }
    : ui

  // Cache for generated documents
  let cachedUSD: USDDocument | null = null
  let cachedOpenAPI: OpenAPIDocument | null = null

  // Generate USD document (lazy)
  const getUSD = (): USDDocument => {
    if (cachedUSD) return cachedUSD

    const result = generateUSD(
      {
        registry: ctx.registry,
        schemaRegistry: ctx.schemaRegistry,
        channels: ctx.channels,
        restResources: ctx.restResources,
        tcpHandlers: ctx.tcpHandlers,
        udpHandlers: ctx.udpHandlers,
        protocolConfig: ctx.protocolConfig,
        ...(ctx.authz ? { authz: ctx.authz } : {}),
      },
      {
        info: {
          title: info?.title ?? 'API Documentation',
          version: info?.version ?? '1.0.0',
          description: info?.description,
          termsOfService: info?.termsOfService,
          contact: info?.contact,
          license: info?.license,
          summary: info?.summary,
        },
        servers,
        protocols,
        contentTypes,
        securitySchemes,
        defaultSecurity,
        tags,
        externalDocs,
        documentation: mergedDocumentation,
        tagGroups: config.tagGroups,
        jsonrpc,
        grpc,
        includeErrorSchemas,
        includeStreamEventSchemas,
        externalPaths,
        externalComponents,
      }
    )

    cachedUSD = result.document
    return cachedUSD
  }

  // Generate OpenAPI document (lazy)
  const getOpenAPI = (): OpenAPIDocument => {
    if (cachedOpenAPI) return cachedOpenAPI

    const usd = getUSD()
    cachedOpenAPI = exportOpenAPI(usd, {
      stripExtensions: true,
      includeWebSocketAsWebhooks: false,
      includeRpcAsEndpoints: false,
      includeStreamsAsEndpoints: false,
    })

    return cachedOpenAPI
  }

  return {
    serveUI: () => {
      const html = generateUIHTML({
        doc: getUSD(),
        basePath,
        ui: mergedUI,
        tagGroups: config.tagGroups,
      })
      return new Response(html, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
        },
      })
    },

    serveUSD: () => {
      const doc = getUSD()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    serveUSDYaml: () => {
      const doc = getUSD()
      const yaml = yamlStringify(doc)
      return new Response(yaml, {
        headers: {
          'Content-Type': 'application/x-yaml',
        },
      })
    },

    serveOpenAPI: () => {
      const doc = getOpenAPI()
      return new Response(JSON.stringify(doc, null, 2), {
        headers: {
          'Content-Type': 'application/json',
        },
      })
    },

    serveUIRuntime: () => {
      const runtime = readBuiltDocsRuntime() ?? generateUIRuntimeJS()
      return new Response(runtime, {
        headers: {
          'Content-Type': 'application/javascript; charset=utf-8',
          'Cache-Control': 'public, max-age=3600',
        },
      })
    },

    serveUIStyles: () => {
      const css = generateUICSS({
        doc: getUSD(),
        basePath,
        ui: mergedUI,
        tagGroups: config.tagGroups,
      })
      return new Response(css, {
        headers: {
          'Content-Type': 'text/css; charset=utf-8',
          'Cache-Control': 'public, max-age=3600',
        },
      })
    },

    getUSDDocument: getUSD,
    getOpenAPIDocument: getOpenAPI,
  }
}
