packages:
  - .

overrides:
  vite: 7.3.6
  fast-uri: ^3.1.5
  undici: ^7.29.0
  postcss: ^8.5.23
  brace-expansion: ^1.1.16
  '@grpc/proto-loader>protobufjs': ^7.6.5
  'recker>protobufjs': ^8.6.6

allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: true
  recker: false
  ssh2: false

minimumReleaseAgeExclude:
  - '@reddb-io/toon@0.13.2'
