import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['test/**/*.unit.test.ts', 'test/**/*.int.test.ts'],
    testTimeout: 30000,
    hookTimeout: 30000,
    // Run test files sequentially to avoid port conflicts
    fileParallelism: false,
    // Ensure clean isolation between tests
    isolate: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      include: [
        'src/adapters/utils/connection-filter.ts',
        'src/channels/channel-manager.ts',
        'src/channels/index.ts',
        'src/core/index.ts',
        'src/docs/generators/errors-types.ts',
        'src/docs/generators/index.ts',
        'src/docs/index.ts',
        'src/docs/openapi/index.ts',
        'src/docs/ui/index.ts',
        'src/dx/health/types.ts',
        'src/dx/logging/types.ts',
        'src/errors/codes.ts',
        'src/errors/factories.ts',
        'src/errors/index.ts',
        'src/graphql/index.ts',
        'src/mcp/tools/index.ts',
        'src/mcp/types.ts',
        'src/metrics/index.ts',
        'src/metrics/registry.ts',
        'src/metrics/types.ts',
        'src/middleware/compose.ts',
        'src/middleware/interceptors/fallback.ts',
        'src/middleware/interceptors/retry.ts',
        'src/proxy/utils/access-control.ts',
        'src/server/fs-routes/index.ts',
        'src/server/fs-routes/resources/index.ts',
        'src/server/fs-routes/resources/types.ts',
        'src/server/fs-routes/rest/index.ts',
        'src/server/fs-routes/rest/types.ts',
        'src/server/fs-routes/tcp/index.ts',
        'src/server/fs-routes/tcp/types.ts',
        'src/server/fs-routes/udp/index.ts',
        'src/server/fs-routes/udp/types.ts',
        'src/server/interceptor-utils.ts',
        'src/server/protocol-aliases.ts',
        'src/server/single-port/index.ts',
        'src/stream/raffel-stream.ts',
        'src/testing/proxy-certs.ts',
        'src/testing/service-suite.ts',
        'src/tracing/index.ts',
        'src/tracing/types.ts',
        'src/types/envelope.ts',
        'src/types/index.ts',
        'src/usd/builder/index.ts',
        'src/usd/export/index.ts',
        'src/usd/index.ts',
        'src/usd/parser/index.ts',
        'src/usd/utils/index.ts',
        'src/utils/id/index.ts',
        'src/validation/adapters/index.ts',
        'src/validation/index.ts',
        'src/validation/types.ts',
      ],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        statements: 90,
      },
    },
  },
})
