/**
 * USD Documentation UI HTML Builder
 *
 * Generates the complete HTML for the USD documentation UI.
 * This module assembles all parts: HTML structure, CSS styles, and embedded JavaScript.
 *
 * Security Note: The embedded JavaScript uses innerHTML for rendering documentation
 * from trusted server-generated spec data. User-provided strings are escaped via esc().
 * This is safe because:
 * 1. The spec object is generated by our code (not user input)
 * 2. All user-visible text is escaped before rendering
 * 3. JSON data is escaped for script embedding to prevent XSS
 */

import type { NavItem, UIGeneratorOptions } from './types.js'
import { generateStyles } from './styles.js'
import { escapeHtml, escapeJsonForScript, generateHeroBackgroundCSS } from './utils.js'
import {
  generateAppContainer,
  generateHeroSection,
  generateIntroductionSection,
  generateSkipLink,
  generateTopNavigation,
  mergeHeroConfig,
} from './html-shell.js'
import {
  generateClientDataScript,
  generateClientRuntimeScript,
} from './client-script/index.js'
import { buildDocsSearchIndex } from '../search-index.js'

/**
 * Generate HTML for USD documentation UI
 */
export function generateUIHTML(options: UIGeneratorOptions): string {
  const { doc, basePath, ui, tagGroups } = options

  // Get USD documentation config from spec
  const usdDocumentation = doc['x-usd']?.documentation

  const theme = ui?.theme ?? 'auto'
  const primaryColor = ui?.primaryColor ?? '#6366f1'
  const logo = ui?.logo ?? usdDocumentation?.logo
  const favicon = ui?.favicon ?? usdDocumentation?.favicon
  const title = doc.info.title
  const version = doc.info.version
  const sidebar = ui?.sidebar
  const docsPages = usdDocumentation?.pages ?? []
  const docsAliases = usdDocumentation?.aliases ?? {}
  const searchIndex = buildDocsSearchIndex(docsPages)
  const externalLinks = (usdDocumentation?.externalLinks ?? []) as Array<{
    title: string
    url: string
  }>
  const navItems = ui?.navbar ?? externalLinks.map(link => ({
    title: link.title,
    href: link.url,
    external: true,
  } satisfies NavItem))
  const footer = ui?.footer ?? usdDocumentation?.footer
  const toc = ui?.toc ?? {}
  const markdown = ui?.markdown ?? {}
  const docsSidebar = ui?.sidebar?.items ?? usdDocumentation?.sidebar ?? []
  const assetMode = ui?.assets?.mode ?? 'inline'
  const assetBasePath = basePath.endsWith('/') ? basePath.slice(0, -1) : basePath
  const docsAssetBasePath = `${assetBasePath}/-/assets`

  // Merge hero config from USD spec and UI config
  const hero = mergeHeroConfig(usdDocumentation, ui?.hero)

  // Get introduction markdown from USD spec
  const introduction = usdDocumentation?.introduction

  // Escape data for embedding in script tag (prevents XSS)
  const escapedSpec = escapeJsonForScript(doc)
  const escapedTagGroups = escapeJsonForScript(tagGroups ?? [])
  const escapedHero = escapeJsonForScript(hero ?? null)
  const escapedSidebar = escapeJsonForScript(sidebar ?? {})
  const escapedIntroduction = escapeJsonForScript(introduction ?? null)
  const escapedDocsPages = escapeJsonForScript(docsPages)
  const escapedDocsAliases = escapeJsonForScript(docsAliases)
  const escapedSearchIndex = escapeJsonForScript(searchIndex)
  const escapedDocsSidebar = escapeJsonForScript(docsSidebar)
  const escapedDocsAssetBasePath = escapeJsonForScript(docsAssetBasePath)
  const escapedFooter = escapeJsonForScript(footer ?? null)
  const escapedToc = escapeJsonForScript(toc)
  const escapedMarkdown = escapeJsonForScript(markdown)

  // Generate hero background CSS
  const heroBackgroundCSS = generateHeroBackgroundCSS(
    primaryColor,
    hero?.background,
    hero?.backgroundImage
  )

  // Generate CSS
  const styles = generateStyles({ primaryColor, heroBackgroundCSS })
  const stylesHtml = assetMode === 'external'
    ? `<link rel="stylesheet" href="${escapeHtml(assetBasePath)}/-/raffel-docs.css">`
    : `<style>
${styles}
  </style>`
  const customCssHtml = normalizeCustomCss(ui?.customCss)
    .map(href => `<link rel="stylesheet" href="${escapeHtml(href)}" data-raffel-custom-css>`)
    .join('\n  ')
  const dataScript = generateClientDataScript(
    escapedSpec,
    escapedTagGroups,
    escapedHero,
    escapedSidebar,
    escapedIntroduction,
    escapedDocsPages,
    escapedDocsAliases,
    escapedSearchIndex,
    escapedDocsSidebar,
    escapedDocsAssetBasePath,
    escapedFooter,
    escapedToc,
    escapedMarkdown
  )
  const runtimeScript = assetMode === 'external'
    ? `<script src="${escapeHtml(assetBasePath)}/-/marked.umd.js"></script>
  <script src="${escapeHtml(assetBasePath)}/-/prism.js"></script>
  <script type="module" src="${escapeHtml(assetBasePath)}/-/raffel-docs.js"></script>`
    : `<script>
${generateClientRuntimeScript()}
  </script>`

  // Generate HTML
  return `<!DOCTYPE html>
<html lang="en" data-theme="${theme}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  ${favicon ? `<link rel="icon" href="${escapeHtml(favicon)}">` : ''}
  ${stylesHtml}
  ${customCssHtml}
</head>
<body>
  ${generateSkipLink(ui?.skipLink)}
  ${generateHeroSection(hero, logo, title, version)}
  ${generateIntroductionSection(introduction)}
  ${generateTopNavigation(logo, title, navItems)}
  ${generateAppContainer(logo, title, sidebar, footer)}
  <script>
${dataScript}
  </script>
  ${runtimeScript}
</body>
</html>`
}

function normalizeCustomCss(customCss: string | string[] | undefined): string[] {
  return (Array.isArray(customCss) ? customCss : customCss ? [customCss] : [])
    .map(href => href.trim())
    .filter(Boolean)
}

/**
 * Generate the reusable docs UI runtime JavaScript.
 */
export function generateUIRuntimeJS(): string {
  return generateClientRuntimeScript()
}

/**
 * Generate the docs UI CSS for the given document/options.
 */
export function generateUICSS(options: UIGeneratorOptions): string {
  const { doc, ui } = options
  const usdDocumentation = doc['x-usd']?.documentation
  const primaryColor = ui?.primaryColor ?? '#6366f1'
  const hero = mergeHeroConfig(usdDocumentation, ui?.hero)
  const heroBackgroundCSS = generateHeroBackgroundCSS(
    primaryColor,
    hero?.background,
    hero?.backgroundImage
  )

  return generateStyles({ primaryColor, heroBackgroundCSS })
}
