/**
 * USD Documentation UI HTML Builder
 *
 * Generates the complete HTML for the USD documentation UI.
 * This module assembles all parts: HTML structure, CSS styles, and embedded JavaScript.
 *
 * Security Note: The embedded JavaScript uses innerHTML for rendering documentation
 * from trusted server-generated spec data. User-provided strings are escaped via esc().
 * This is safe because:
 * 1. The spec object is generated by our code (not user input)
 * 2. All user-visible text is escaped before rendering
 * 3. JSON data is escaped for script embedding to prevent XSS
 */

import type { BreadcrumbsConfig, NavItem, OpenGraphConfig, PageNavConfig, TryItOutConfig, UIGeneratorOptions } from './types.js'

const _startupTs = Date.now()
import { generateStyles } from './styles.js'
import { escapeHtml, escapeJsonForScript, generateHeroBackgroundCSS } from './utils.js'
import {
  generateAppContainer,
  generateHeroSection,
  generateIntroductionSection,
  generateSkipLink,
  generateTopNavigation,
  mergeHeroConfig,
} from './html-shell.js'
import {
  generateClientDataScript,
  generateInlineRuntimeDependencyScripts,
  generateClientRuntimeScript,
} from './client-script/index.js'
import { buildDocsSearchIndex } from '../search-index.js'
import { buildSerializedResponseExamples } from './response-examples.js'

/**
 * Generate HTML for USD documentation UI
 */
export function generateUIHTML(options: UIGeneratorOptions): string {
  const { doc, basePath, ui, tagGroups } = options

  // Get USD documentation config from spec
  const usdDocumentation = doc['x-usd']?.documentation

  const theme = ui?.theme ?? 'auto'
  const primaryColor = ui?.primaryColor ?? '#6366f1'
  const logo = ui?.logo ?? usdDocumentation?.logo
  const favicon = ui?.favicon ?? usdDocumentation?.favicon
  const title = doc.info.title
  const version = doc.info.version
  const openGraph = resolveOpenGraphConfig(ui?.openGraph, usdDocumentation?.openGraph, doc.info)
  const sidebar = ui?.sidebar
  const docsPages = usdDocumentation?.pages ?? []
  const docsAliases = usdDocumentation?.aliases ?? {}
  const searchIndex = buildDocsSearchIndex(docsPages)
  const externalLinks = (usdDocumentation?.externalLinks ?? []) as Array<{
    title: string
    url: string
  }>
  const navItems = ui?.navbar ?? externalLinks.map(link => ({
    title: link.title,
    href: link.url,
    external: true,
  } satisfies NavItem))
  const footer = ui?.footer ?? usdDocumentation?.footer
  const toc = ui?.toc ?? {}
  const markdown = ui?.markdown ?? {}
  const breadcrumbs = normalizeBreadcrumbsConfig(ui?.breadcrumbs)
  const docsSidebar = ui?.sidebar?.items ?? usdDocumentation?.sidebar ?? []
  const pageNav = normalizePageNav(ui?.pageNav)
  const assetMode = ui?.assets?.mode ?? 'inline'
  const assetBasePath = basePath.endsWith('/') ? basePath.slice(0, -1) : basePath
  const docsAssetBasePath = `${assetBasePath}/-/assets`

  // Merge hero config from USD spec and UI config
  const hero = mergeHeroConfig(usdDocumentation, ui?.hero)

  // Get introduction markdown from USD spec
  const introduction = usdDocumentation?.introduction

  // Escape data for embedding in script tag (prevents XSS)
  const escapedSpec = escapeJsonForScript(doc)
  const escapedTagGroups = escapeJsonForScript(tagGroups ?? [])
  const escapedHero = escapeJsonForScript(hero ?? null)
  const escapedSidebar = escapeJsonForScript(sidebar ?? {})
  const escapedIntroduction = escapeJsonForScript(introduction ?? null)
  const escapedDocsPages = escapeJsonForScript(docsPages)
  const escapedDocsAliases = escapeJsonForScript(docsAliases)
  const escapedSearchIndex = escapeJsonForScript(searchIndex)
  const escapedDocsSidebar = escapeJsonForScript(docsSidebar)
  const escapedDocsAssetBasePath = escapeJsonForScript(docsAssetBasePath)
  const escapedFooter = escapeJsonForScript(footer ?? null)
  const escapedToc = escapeJsonForScript(toc)
  const escapedMarkdown = escapeJsonForScript(markdown)
  const escapedDocsRepo = escapeJsonForScript(ui?.docsRepo ?? null)
  const escapedBreadcrumbs = escapeJsonForScript(breadcrumbs)
  const escapedPageNav = escapeJsonForScript(pageNav)
  const escapedMermaid = escapeJsonForScript(normalizeMermaidConfig(ui?.mermaid))
  const escapedResponseExamples = escapeJsonForScript(buildSerializedResponseExamples(doc as Record<string, any>))
  const escapedTryIt = escapeJsonForScript(normalizeTryItOut(ui?.tryItOut, assetBasePath))

  // Generate hero background CSS
  const heroBackgroundCSS = generateHeroBackgroundCSS(
    primaryColor,
    hero?.background,
    hero?.backgroundImage
  )

  // Generate CSS
  const styles = generateStyles({ primaryColor, heroBackgroundCSS })
  const stylesHtml = assetMode === 'external'
    ? `<link rel="stylesheet" href="${escapeHtml(assetBasePath)}/-/raffel-docs.css">`
    : `<style>
${styles}
  </style>`
  const customCssHtml = normalizeCustomCss(ui?.customCss)
    .map(href => `<link rel="stylesheet" href="${escapeHtml(href)}" data-raffel-custom-css>`)
    .join('\n  ')
  const openGraphHtml = generateOpenGraphTags(openGraph)
  const dataScript = generateClientDataScript(
    escapedSpec,
    escapedTagGroups,
    escapedHero,
    escapedSidebar,
    escapedIntroduction,
    escapedDocsPages,
    escapedDocsAliases,
    escapedSearchIndex,
    escapedDocsSidebar,
    escapedDocsAssetBasePath,
    escapedFooter,
    escapedToc,
    escapedMarkdown,
    escapedDocsRepo,
    escapedBreadcrumbs,
    escapedPageNav,
    escapedMermaid,
    escapedResponseExamples,
    escapedTryIt
  )
  const runtimeScript = assetMode === 'external'
    ? `<script>
  // Defensive asset probe: if a sibling JS asset returns HTML, the wildcard
  // SPA route is shadowing it. Surfaces a clear error instead of letting the
  // module loader fail with an opaque syntax error.
  (function probeAssets(){
    var paths = ['${escapeHtml(assetBasePath)}/-/marked.umd.js','${escapeHtml(assetBasePath)}/-/raffel-docs.js','${escapeHtml(assetBasePath)}/-/sidebar-tree.js'];
    paths.forEach(function(p){
      fetch(p, { method: 'HEAD' }).then(function(r){
        var ct = (r.headers.get('content-type') || '').toLowerCase();
        if (ct.indexOf('html') >= 0) {
          console.error('[raffel-docs] Asset not mounted: ' + p + ' returned ' + ct + '. Wire the corresponding handler (e.g. handlers.serveUI*) at this path, or use mountUSDDocs() to do it automatically.');
        }
      }).catch(function(){});
    });
  })();
  </script>
  <script type="importmap">
  {
    "imports": {
      "${escapeHtml(assetBasePath)}/-/sidebar-tree.js": "${escapeHtml(assetBasePath)}/-/sidebar-tree.js?v=${_startupTs}",
      "${escapeHtml(assetBasePath)}/-/marked-renderer.js": "${escapeHtml(assetBasePath)}/-/marked-renderer.js?v=${_startupTs}",
      "${escapeHtml(assetBasePath)}/-/protocol-console.js": "${escapeHtml(assetBasePath)}/-/protocol-console.js?v=${_startupTs}",
      "${escapeHtml(assetBasePath)}/-/code-block-toolbar.js": "${escapeHtml(assetBasePath)}/-/code-block-toolbar.js?v=${_startupTs}",
      "${escapeHtml(assetBasePath)}/-/page-nav.js": "${escapeHtml(assetBasePath)}/-/page-nav.js?v=${_startupTs}",
      "${escapeHtml(assetBasePath)}/-/search-modal.js": "${escapeHtml(assetBasePath)}/-/search-modal.js?v=${_startupTs}"
    }
  }
  </script>
  <script src="${escapeHtml(assetBasePath)}/-/marked.umd.js"></script>
  <script src="${escapeHtml(assetBasePath)}/-/prism.js"></script>
  <script type="module" data-raffel-runtime="external" src="${escapeHtml(assetBasePath)}/-/raffel-docs.js?v=${_startupTs}"></script>`
    : `${generateInlineRuntimeDependencyScripts()}
  <script data-raffel-runtime="inline">
${generateClientRuntimeScript()}
  </script>`

  // Generate HTML
  return `<!DOCTYPE html>
<html lang="en" data-theme="${theme}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  ${favicon ? `<link rel="icon"${isIcoFaviconUrl(favicon) ? ' type="image/x-icon"' : ''} href="${escapeHtml(favicon)}">` : ''}
  ${openGraphHtml}
  ${stylesHtml}
  ${customCssHtml}
</head>
<body>
  ${generateSkipLink(ui?.skipLink)}
  ${generateHeroSection(hero, logo, title, version, generateTopNavigation(logo, title, navItems))}
  ${generateIntroductionSection(introduction)}
  ${hero ? '' : generateTopNavigation(logo, title, navItems)}
  ${generateAppContainer(logo, title, sidebar, footer)}
  <script>
${dataScript}
  </script>
  ${runtimeScript}
</body>
</html>`
}

/**
 * Normalize the `ui.breadcrumbs` option into a concrete config object.
 *
 *   undefined / true  → enabled with default `hideOnHome: true`.
 *   false             → `{ enabled: false }`.
 *   { ... }           → enabled with overrides applied on top of defaults.
 */
function normalizeBreadcrumbsConfig(
  raw: boolean | BreadcrumbsConfig | undefined
): { enabled: boolean; hideOnHome: boolean } {
  if (raw === false) return { enabled: false, hideOnHome: true }
  if (raw === undefined || raw === true) return { enabled: true, hideOnHome: true }
  return {
    enabled: true,
    hideOnHome: raw.hideOnHome !== false,
  }
}

function normalizeCustomCss(customCss: string | string[] | undefined): string[] {
  return (Array.isArray(customCss) ? customCss : customCss ? [customCss] : [])
    .map(href => href.trim())
    .filter(Boolean)
}

function resolveOpenGraphConfig(
  uiOpenGraph: OpenGraphConfig | undefined,
  usdOpenGraph: OpenGraphConfig | undefined,
  info: { title?: string; description?: string } | undefined,
): OpenGraphConfig {
  return {
    title: firstDefined(uiOpenGraph?.title, usdOpenGraph?.title, info?.title),
    description: firstDefined(uiOpenGraph?.description, usdOpenGraph?.description, info?.description),
    type: firstDefined(uiOpenGraph?.type, usdOpenGraph?.type, 'website'),
    url: firstDefined(uiOpenGraph?.url, usdOpenGraph?.url),
    image: firstDefined(uiOpenGraph?.image, usdOpenGraph?.image),
    imageAlt: firstDefined(uiOpenGraph?.imageAlt, usdOpenGraph?.imageAlt),
    siteName: firstDefined(uiOpenGraph?.siteName, usdOpenGraph?.siteName),
    locale: firstDefined(uiOpenGraph?.locale, usdOpenGraph?.locale),
  }
}

function generateOpenGraphTags(openGraph: OpenGraphConfig): string {
  const tags: Array<[string, string | undefined]> = [
    ['og:title', openGraph.title],
    ['og:description', openGraph.description],
    ['og:type', openGraph.type],
    ['og:url', openGraph.url],
    ['og:image', openGraph.image],
    ['og:image:alt', openGraph.image ? openGraph.imageAlt : undefined],
    ['og:site_name', openGraph.siteName],
    ['og:locale', openGraph.locale],
  ]

  return tags
    .filter(([, content]) => Boolean(content))
    .map(([property, content]) => `<meta property="${property}" content="${escapeHtml(content!)}">`)
    .join('\n  ')
}

function isIcoFaviconUrl(favicon: string): boolean {
  return favicon.replace(/[?#].*$/, '').toLowerCase().endsWith('.ico')
}

function firstDefined(...values: Array<string | undefined>): string | undefined {
  for (const value of values) {
    if (typeof value !== 'string') continue
    return value.trim()
  }
  return undefined
}

function normalizePageNav(value: boolean | PageNavConfig | undefined): { enabled: boolean; hide: string[] } {
  if (value === false) return { enabled: false, hide: [] }
  if (value === true || value === undefined || value === null) return { enabled: true, hide: [] }
  const hide = Array.isArray(value.hide)
    ? value.hide.map(item => String(item)).filter(Boolean)
    : []
  return { enabled: true, hide }
}

function normalizeTryItOut(value: boolean | TryItOutConfig | undefined, basePath: string): Record<string, unknown> {
  if (!value) return { enabled: false, mode: 'direct', proxyUrl: `${basePath}/-/request` }
  if (value === true) return { enabled: true, mode: 'direct', proxyUrl: `${basePath}/-/request` }
  return {
    enabled: true,
    mode: value.mode === 'proxy' ? 'proxy' : 'direct',
    proxyUrl: `${basePath}/-/request`,
  }
}

/**
 * Generate the reusable docs UI runtime JavaScript.
 */
export function generateUIRuntimeJS(): string {
  return generateClientRuntimeScript()
}

/**
 * Generate the docs UI CSS for the given document/options.
 */
export function generateUICSS(options: UIGeneratorOptions): string {
  const { doc, ui } = options
  const usdDocumentation = doc['x-usd']?.documentation
  const primaryColor = ui?.primaryColor ?? '#6366f1'
  const hero = mergeHeroConfig(usdDocumentation, ui?.hero)
  const heroBackgroundCSS = generateHeroBackgroundCSS(
    primaryColor,
    hero?.background,
    hero?.backgroundImage
  )

  return generateStyles({ primaryColor, heroBackgroundCSS })
}

const DEFAULT_MERMAID_CDN_SRC = 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js'

/**
 * Normalize the `ui.mermaid` option into a concrete `{ enabled, src }` shape
 * the runtime can read off `window.__RAFFEL_DOCS__.mermaidConfig`.
 *
 *   undefined / true → enabled with the default CDN source.
 *   false            → disabled. The runtime will leave `.mermaid` blocks
 *                      in their fallback state without attempting to load
 *                      the library.
 *   { src }          → enabled with a pinned/self-hosted script URL.
 */
function normalizeMermaidConfig(option: unknown): { enabled: boolean; src: string; viewer: boolean } {
  if (option === false) return { enabled: false, src: '', viewer: false }
  if (option && typeof option === 'object') {
    const obj = option as { src?: string; viewer?: boolean }
    return {
      enabled: true,
      src: typeof obj.src === 'string' && obj.src ? obj.src : DEFAULT_MERMAID_CDN_SRC,
      viewer: obj.viewer !== false,
    }
  }
  return { enabled: true, src: DEFAULT_MERMAID_CDN_SRC, viewer: true }
}
