/**
 * Shared TLS resolution utility.
 *
 * Resolves TLS credentials from three sources (in priority order):
 * 1. Inline content (string | Buffer)
 * 2. File path (K8s Secret volume mounts)
 * 3. Environment variable (base64-encoded PEM)
 *
 * When no source is provided for key/cert, a self-signed certificate
 * is auto-generated for local development.
 */

import { readFile } from 'node:fs/promises'

export interface TlsOptions {
  /** PEM-encoded private key (inline) */
  key?: string | Buffer
  /** PEM-encoded certificate (inline) */
  cert?: string | Buffer
  /** PEM-encoded CA certificate (inline) */
  ca?: string | Buffer

  /** Path to PEM-encoded private key file */
  keyFile?: string
  /** Path to PEM-encoded certificate file */
  certFile?: string
  /** Path to PEM-encoded CA certificate file */
  caFile?: string

  /** Environment variable name containing base64-encoded PEM private key */
  keyEnv?: string
  /** Environment variable name containing base64-encoded PEM certificate */
  certEnv?: string
  /** Environment variable name containing base64-encoded PEM CA certificate */
  caEnv?: string

  /** Hostname for auto-generated self-signed certificate (default: 'localhost') */
  host?: string
}

export interface ResolvedTls {
  key: Buffer
  cert: Buffer
  ca?: Buffer
  autoGenerated?: boolean
}

async function resolveField(
  inline?: string | Buffer,
  file?: string,
  env?: string,
  label?: string
): Promise<Buffer> {
  if (inline != null) {
    return typeof inline === 'string' ? Buffer.from(inline) : inline
  }

  if (file) {
    return readFile(file)
  }

  if (env) {
    const value = process.env[env]
    if (!value) {
      throw new Error(`TLS ${label ?? 'field'}: env var "${env}" is not set`)
    }
    return Buffer.from(value, 'base64')
  }

  throw new Error(`TLS ${label ?? 'field'}: no source provided (inline, file, or env)`)
}

function hasSource(inline?: string | Buffer, file?: string, env?: string): boolean {
  return inline != null || file != null || env != null
}

export async function resolveTlsOptions(tls: TlsOptions): Promise<ResolvedTls> {
  const hasKey = hasSource(tls.key, tls.keyFile, tls.keyEnv)
  const hasCert = hasSource(tls.cert, tls.certFile, tls.certEnv)

  if (!hasKey && !hasCert) {
    const { generateCertificate } = await import('./certs.js')
    const generated = await generateCertificate(tls.host ?? 'localhost')
    return {
      key: Buffer.from(generated.key),
      cert: Buffer.from(generated.cert),
      ca: generated.ca ? Buffer.from(generated.ca) : undefined,
      autoGenerated: true,
    }
  }

  const [key, cert] = await Promise.all([
    resolveField(tls.key, tls.keyFile, tls.keyEnv, 'key'),
    resolveField(tls.cert, tls.certFile, tls.certEnv, 'cert'),
  ])

  const ca = hasSource(tls.ca, tls.caFile, tls.caEnv)
    ? await resolveField(tls.ca, tls.caFile, tls.caEnv, 'ca')
    : undefined

  return { key, cert, ca }
}
